# Generated by Django 3.1 on 2023-01-14 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedData',
            fields=[
                ('url_id', models.AutoField(primary_key=True, serialize=False)),
                ('url_input', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=200)),
                ('product_title', models.CharField(max_length=500)),
                ('product_description', models.TextField()),
                ('product_price', models.CharField(max_length=200)),
                ('scraped_date', models.DateTimeField(verbose_name='date_scraped')),
            ],
        ),
    ]
