# Generated by Django 3.1 on 2023-01-14 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapeddata',
            name='product_image',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='product_rating',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
